trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'dev'
    values:
      - dev
      - prod

variables:
  - group: 'ADF-$(parameters.environment)'

stages:
  - stage: Validate
    displayName: Validate ${{ parameters.environment }} Deployment
    jobs:
      - job: ValidateTemplate
        displayName: Validate Bicep Template
        pool:
          vmImage: ubuntu-latest
        steps:

          - task: PublishBuildArtifacts@1

          - task: AzureResourceManagerTemplateDeployment@3
            name: ValidateBicepWhatIf
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Pay-as-you-go-sc'
              subscriptionId: '6f0f938c-0599-4b69-9b56-09468ec24549'        # from variable group
              action: 'What If'
              resourceGroupName: 'khrg'
              location: 'EastUS'
              templateLocation: 'Linked artifact'
              csmFile: 'main.bicep'
              csmParametersFile: 'parameters/parameters-${{ parameters.environment }}.json'

  - stage: Deploy
    displayName: Deploy to ${{ parameters.environment }}
    dependsOn: Validate
    condition: succeeded()
    jobs:
      - deployment: DeployADF
        environment: '${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  name: DeployBicep
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'Pay-as-you-go-sc'
                    subscriptionId: '6f0f938c-0599-4b69-9b56-09468ec24549'        # from variable group
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'khrg'
                    location: 'EastUS'
                    templateLocation: 'Linked artifact'
                    csmFile: 'main.bicep'
                    csmParametersFile: 'parameters/parameters-${{ parameters.environment }}.json'
