trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'dev'
    values:
      - dev
      # - prod
        
stages:
  - stage: CreateAzureVNET
    displayName: 'CreateSQLServer'
    jobs:
      - deployment: CreateSQLServer
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Bicep Artifact'
                  inputs:
                    pathtoPublish: '$(System.DefaultWorkingDirectory)'
                    artifactName: 'bicep'
                    publishLocation: 'Container'

                - script: |
                      echo "Files in current directory:"
                      ls -R
                      pwd
                  displayName: 'List files'


                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Bicep to Deploy SQLvServer'
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'Pay-as-you-go-sc'
                    subscriptionId: '6f0f938c-0599-4b69-9b56-09468ec24549'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'khrg'
                    location: 'EastUS'
                    templateLocation: 'Linked artifact'
                    csmFile: 'main.bicep'
                    csmParametersFile: 'parameters/parameters-dev.json'
                    deploymentMode: 'Incremental'