trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'dev'
    values:
      - dev
      # - prod


stages:
  - stage: Validate
    displayName: Validate ${{ parameters.environment }} Deployment
    jobs:
      - job: ValidateTemplate
        displayName: Validate Bicep Template
        steps:

                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Bicep Artifact'
                  inputs:
                    pathtoPublish: '$(System.DefaultWorkingDirectory)'
                    artifactName: 'bicep'
                    publishLocation: 'Container'

  - stage: Deploy
    displayName: Deploy to ${{ parameters.environment }}
    jobs:
      - deployment: DeployADF
        environment: '${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:   
                
                - script: |
                      echo "Files in current directory:"
                      ls -R
                      pwd
                  displayName: 'List files'

                - task: AzureResourceManagerTemplateDeployment@3
                  name: DeployBicep
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'Pay-as-you-go-sc'
                    subscriptionId: '6f0f938c-0599-4b69-9b56-09468ec24549'        # from variable group
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'khrg'
                    location: 'EastUS'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(System.DefaultWorkingDirectory)/main.bicep'
                    csmParametersFile: '$(System.DefaultWorkingDirectory)/parameters/parameters-${{ parameters.environment }}.json'
                    # overrideParameters: '-location "EastUS"'
                    deploymentMode: 'Incremental'
